### ISSUE TITLE
Getting the Errormessage on one MacOS Computer (on two it runs perfect

### ISSUE THREAD

**Issue by thorstenstueker** [Bouni/kicad-jlcpcb-tools#192]
Traceback (most recent call last):

File "/Users/thorstenstueker/Documents/KiCad/6.0/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/plugin.py", line 21, in Run
dialog = JLCPCBTools(None)

File "/Users/thorstenstueker/Documents/KiCad/6.0/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/mainwindow.py", line 558, in __init__
self.init_store()

File "/Users/thorstenstueker/Documents/KiCad/6.0/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/mainwindow.py", line 574, in init_store
self.populate_footprint_list()

File "/Users/thorstenstueker/Documents/KiCad/6.0/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/mainwindow.py", line 647, in populate_footprint_list
details = self.library.get_part_details(numbers)

File "/Users/thorstenstueker/Documents/KiCad/6.0/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/library.py", line 316, in get_part_details
return cur.execute(

sqlite3.OperationalError: no such table: parts

Kickt 6.0.2
MacOS: Monterey 12.4

This Bug I have not on two other Mac OS Computers with the same environment around and the same configuration and the same OS. All are Mac M1 ARM Computers.

**Comment by thorstenstueker** [comment]
Got it running: completely deinstalled Plugin and reinstalled it after. Works immediately. Sorry-
