### ISSUE TITLE
Plugin fails to load on 7.99

### ISSUE THREAD

**Issue by triglav-modular** [Bouni/kicad-jlcpcb-tools#326]
**Describe the bug**
Plugin fails to load on 7.99

**To Reproduce**
1. Install 7.99 Nightly
2. Run the plugin. It will load, but no components show up in the window.
3. Close plugin.
4. Opening the plugin again produces the following error message:

```
**Exception on python action plugin code**

Traceback (most recent call last):

File "/Users/<username>/Documents/KiCad/7.99/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/plugin.py", line 21, in Run
dialog = JLCPCBTools(None)

File "/Users/<username>/Documents/KiCad/7.99/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/mainwindow.py", line 498, in __init__
self.init_store()

File "/Users/<username>/Documents/KiCad/7.99/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/mainwindow.py", line 512, in init_store
self.store = Store(self, self.project_path)

File "/Users/<username>/Documents/KiCad/7.99/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/store.py", line 31, in __init__
self.update_from_board()

File "/Users/<username>/Documents/KiCad/7.99/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/store.py", line 201, in update_from_board
get_lcsc_value(fp),

File "/Users/<username>/Documents/KiCad/7.99/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/helpers.py", line 110, in get_lcsc_value
for value in fp.GetProperties().values():

AttributeError: 'FOOTPRINT' object has no attribute 'GetProperties'
```

# KiCad Version

```
Application: KiCad PCB Editor x86_64 on x86_64

Version: 7.99.0-1900-g89780d353a, release build

Libraries:
	wxWidgets 3.2.2
	FreeType 2.13.0
	HarfBuzz 7.3.0
	FontConfig 2.14.2
	libcurl/8.1.2 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.53.0

Platform: macOS Version 14.0 (Build 23A5286i), 64 bit, Little endian, wxMac

Build Info:
	Date: Jul 16 2023 02:04:08
	wxWidgets: 3.2.2 (wchar_t,wx containers)
	Boost: 1.82.0
	OCC: 7.7.0
	Curl: 7.77.0
	ngspice: 40
	Compiler: Clang 13.0.0 with C++ ABI 1002

Build settings:

```

**Comment by Bouni** [comment]
Th Kicad devs broke the API again so I have to figure out what I need to do in order to get the same functionality. That take some time ...
