### ISSUE TITLE
Solved by upgrading sqllite3 2024.04.03: sqlite3.OperationalError: no such tokenizer: trigram

### ISSUE THREAD

**Issue by JLA4444** [Bouni/kicad-jlcpcb-tools#461]
**Describe the bug**

Traceback (most recent call last):
  File "/home/h-tech/.local/share/kicad/8.0/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/mainwindow.py", line 927, in select_part
    PartSelectorDialog(self, selection).ShowModal()
  File "/home/h-tech/.local/share/kicad/8.0/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/partselector.py", line 515, in __init__
    self.search(None)
  File "/home/h-tech/.local/share/kicad/8.0/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/partselector.py", line 587, in search
    result = self.parent.library.search(parameters)
  File "/home/h-tech/.local/share/kicad/8.0/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/library.py", line 193, in search
    return cur.execute(query).fetchall()
sqlite3.OperationalError: no such tokenizer: trigram

**To Reproduce**
1. Open 2024.04.03
2. Select component
3. Press Assign LCSC number
4. Error appears in terminal

**Expected behavior**
As in 2023.09 version

# KiCad Version

```
Application: KiCad PCB Editor x86_64 on x86_64

Version: 8.0.2-unknown-202404301934~c179f4d4f1~ubuntu20.04.1, release build

Libraries:
	wxWidgets 3.2.1
	FreeType 2.10.1
	HarfBuzz 2.6.4
	FontConfig 2.13.1
	libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3

Platform: Ubuntu 20.04.6 LTS, 64 bit, Little endian, wxGTK, X11, ubuntu, x11

Build Info:
	Date: Apr 30 2024 19:34:51
	wxWidgets: 3.2.1 (wchar_t,wx containers) GTK+ 3.24
	Boost: 1.71.0
	OCC: 7.6.3
	Curl: 7.68.0
	ngspice: 42
	Compiler: GCC 9.4.0 with C++ ABI 1013

Build settings:

```

**Comment by JLA4444** [comment]
This was solved by upgrading the SQLite3 version
